### ISSUE TITLE
Upgrade

### ISSUE THREAD

**Issue by abrehmanjaffri** [mt-ag/apex-simple-form-builder#1]
Can we have the app with the latest Uwe Simon JSON region plugin? with an example of cascading lists

**Comment by nielsdebr** [comment]
We are shipping the Simple Process Starter App with 0.9.5 of the JSON plugin in Flows for APEX 24.1. You can easily install a newer version of the plugin yourself to leverage cascading select lists. Contact Uwe directly for an example.
